---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(rstan)
library(glue)
library(shinystan)
```

```{r}
partidas_ids <- read.csv("../data/2014_partidas_ids.csv", header = TRUE, encoding = 'UTF-8')
times_ids    <- read.csv("../data/2014_times.csv", header = TRUE, encoding = 'UTF-8')
```

```{r}
partidas_ids <- partidas_ids |>
  select(
    "Casa",
    "Visitante",
    "PlacarCasa",
    "PlacarVisitante",
    "Rodada"
  )

times_ids <- times_ids |>
  select(
    "ID",
    "Nome"
  )
```

```{r}
data <- partidas_ids |> 
  inner_join(times_ids, join_by("Casa" == "ID")) |> 
  inner_join(times_ids, join_by("Visitante" == "ID")) |>
  rename(
    "home_team_id"    = "Casa",
    "away_team_id"    = "Visitante",
    "home_team_score" = "PlacarCasa",
    "away_team_score" = "PlacarVisitante",
    "home_team_name"  = "Nome.x",
    "away_team_name"  = "Nome.y",
    "round"           = "Rodada"
  )
```

```{r}
data <- data |> 
  mutate(
    home_team_points = case_when(
        home_team_score >  away_team_score ~ 3,
        home_team_score == away_team_score ~ 1,
        home_team_score <  away_team_score ~ 0
        ),
    away_team_points = case_when(
        away_team_score >  home_team_score ~ 3,
        away_team_score == home_team_score ~ 1,
        away_team_score <  home_team_score ~ 0
    ),
    home_team_id = case_when(
       home_team_id == 262 ~ 1,
       home_team_id == 263 ~ 2,
       home_team_id == 264 ~ 3,
       home_team_id == 265 ~ 4,
       home_team_id == 266 ~ 5,
       home_team_id == 275 ~ 6,
       home_team_id == 276 ~ 7,
       home_team_id == 277 ~ 8,
       home_team_id == 282 ~ 9,
       home_team_id == 283 ~ 10,
       home_team_id == 284 ~ 11,
       home_team_id == 285 ~ 12,
       home_team_id == 287 ~ 13,
       home_team_id == 288 ~ 14,
       home_team_id == 290 ~ 15,
       home_team_id == 292 ~ 16,
       home_team_id == 293 ~ 17,
       home_team_id == 294 ~ 18,
       home_team_id == 315 ~ 19,
       home_team_id == 316 ~ 20
    ),
    away_team_id = case_when(
       away_team_id == 262 ~ 1,
       away_team_id == 263 ~ 2,
       away_team_id == 264 ~ 3,
       away_team_id == 265 ~ 4,
       away_team_id == 266 ~ 5,
       away_team_id == 275 ~ 6,
       away_team_id == 276 ~ 7,
       away_team_id == 277 ~ 8,
       away_team_id == 282 ~ 9,
       away_team_id == 283 ~ 10,
       away_team_id == 284 ~ 11,
       away_team_id == 285 ~ 12,
       away_team_id == 287 ~ 13,
       away_team_id == 288 ~ 14,
       away_team_id == 290 ~ 15,
       away_team_id == 292 ~ 16,
       away_team_id == 293 ~ 17,
       away_team_id == 294 ~ 18,
       away_team_id == 315 ~ 19,
       away_team_id == 316 ~ 20
    )
  )
```

```{r}
write.csv(data, file = "../data/2014_partidas_tidy.csv")
```


```{r}
prg <- stan_model(file = "../models/stan/modelo-poisson-misto.stan")

dados_list <- list(
  G  = 380,
  T  = 20,
  h  = data$home_team_id,
  a  = data$away_team_id,
  y1 = data$home_team_score,
  y2 = data$away_team_score
)

iter <- 4000

fit_sim <- sampling(prg, data = dados_list, chains = 1, iter = iter, cores = 1, refresh = 100)
```


```{r}
home_team_predict <- c()
away_team_predict <- c()

home_team_predict_025 <- c()
away_team_predict_025 <- c()

home_team_predict_975 <- c()
away_team_predict_975 <- c()

list_of_draws <- extract(fit_sim, pars = c("y1_tilde", "y2_tilde"))
sample_size <- dim(list_of_draws$y1_tilde)[1]
G <- 380

for(i in 1:G) {
  home_team_points_vec <- c()
  away_team_points_vec <- c()
  
  for(j in 1:sample_size) {
    home_team_score <- list_of_draws$y1_tilde[j, i]
    away_team_score <- list_of_draws$y2_tilde[j, i]
    
    if (home_team_score > away_team_score) {
      home_team_points <- 3
      away_team_points <- 0
    } else if (home_team_score < away_team_score) {
      home_team_points <- 0
      away_team_points <- 3
    } else {
      home_team_points <- 1
      away_team_points <- 1
    }
    
    home_team_points_vec <- append(home_team_points_vec, home_team_points)
    away_team_points_vec <- append(away_team_points_vec, away_team_points)
    
  }
  
  home_team_points_sum <- sum(home_team_points_vec)
  away_team_points_sum <- sum(away_team_points_vec)
  
  if (home_team_points_sum > away_team_points_sum) {
    home_team_point_in_round <- 3
    away_team_point_in_round <- 0
  } else if (home_team_points_sum < away_team_points_sum) {
    home_team_point_in_round <- 0
    away_team_point_in_round <- 3
  } else {
    home_team_point_in_round <- 1
    away_team_point_in_round <- 1     
  }
  
  home_team_predict <- append(home_team_predict, home_team_point_in_round)
  away_team_predict <- append(away_team_predict, away_team_point_in_round)
  
  home_team_predict_025 <- append(home_team_predict_025, quantile(home_team_points_vec, 0.025))
  away_team_predict_025 <- append(away_team_predict_025, quantile(away_team_points_vec, 0.025))
  
  home_team_predict_975 <- append(home_team_predict_975, quantile(home_team_points_vec, 0.975))
  away_team_predict_975 <- append(away_team_predict_975, quantile(away_team_points_vec, 0.975))
  
}
```

```{r}
data <- data |>
  mutate(
    home_team_predict = home_team_predict,
    away_team_predict = away_team_predict,
    
    home_team_predict_025 = home_team_predict_025,
    away_team_predict_025 = away_team_predict_025,
    
    home_team_predict_975 = home_team_predict_975,
    away_team_predict_975 = away_team_predict_975
  )
```

```{r}
data_by_team <- data |> select(
  "round",
  "home_team_name",
  "away_team_name",
  "home_team_points",
  "away_team_points",
  "home_team_predict",
  "away_team_predict",
  "home_team_predict_025",
  "away_team_predict_025",
  "home_team_predict_975",
  "away_team_predict_975"
  
) |> 
  pivot_longer(
  cols = ends_with("name")
) |> mutate(
  points = case_when(
      name ==  "home_team_name" ~ home_team_points,
      name ==  "away_team_name" ~ away_team_points
      ),
  points_predict = case_when(
      name ==  "home_team_name" ~ home_team_predict,
      name ==  "away_team_name" ~ away_team_predict
      ),
  points_predict_025 = case_when(
      name ==  "home_team_name" ~ home_team_predict_025,
      name ==  "away_team_name" ~ away_team_predict_025
      ),
  points_predict_975 = case_when(
      name ==  "home_team_name" ~ home_team_predict_975,
      name ==  "away_team_name" ~ away_team_predict_975
      ),
) |>
  rename(
  team = value
) |>
select(
  round,
  team,
  points,
  points_predict,
  points_predict_025,
  points_predict_975
) |> group_by(
  team
) |>
mutate(
  cumulative_points = order_by(round, cumsum(points)),
  cumulative_points_predict = order_by(round, cumsum(points_predict)),
  cumulative_points_predict_025 = order_by(round, cumsum(points_predict_025)),
  cumulative_points_predict_975 = order_by(round, cumsum(points_predict_975))
)
```

```{r}
ggplot(data = data_by_team, mapping = aes(x = round)) + 
  geom_line(mapping = aes(y = cumulative_points), color = "red") +
  geom_line(mapping = aes(y = cumulative_points_predict), color = "blue") +
  geom_ribbon(mapping = aes(ymin = cumulative_points_predict_025, ymax = cumulative_points_predict_975), linetype=2, alpha=0.1) + 
  facet_wrap(~ team)
```

