---
title: "Modelo binomial negativa JAGs"
output: html_notebook
---
# Código do modelo no Jags

```{r echo=TRUE}
cat("
model
{   
  for(g in 1:G) {  
    y1[g] ~  dnegbin(bn_size / (lambda1[g] + bn_size), bn_size)
    lambda1[g] = exp(home + att[h[g]] + def[a[g]]) # h e a são passados nos dados
    
    y1_tilde[g] ~  dnegbin(bn_size / (lambda1[g] + bn_size), bn_size)

    y2[g] ~  dnegbin(bn_size / (lambda2[g] + bn_size), bn_size)
    lambda2[g] = exp(att[a[g]] + def[h[g]])

    y2_tilde[g] ~  dnegbin(bn_size / (lambda1[g] + bn_size), bn_size)
  }
  
  for(t in 1:(T-1)) {
    att_raw[t] ~ dnorm(mu_att, tau_att)  ## tau = 1/sigma2
    def_raw[t] ~ dnorm(mu_def, tau_def)
    att[t] = att_raw[t]
    def[t] = def_raw[t]
  }
  
  att[T] = 0
  def[T] = 0
  
  tau_eff = 1/sigma_sq_eff ## sigma_sq_eff passado nos dados
  tau_size = 1/sigma_sq_eff_size ## sigma_sq_eff_size passado nos dados
   
  mu_att ~ dnorm(0, tau_eff)
  mu_def ~ dnorm(0, tau_eff)
  
  home ~ dnorm(0, tau_eff)
  
  bn_size ~ dt(0, sigma_sq_eff_size, 1) T(0, ) ## df = 1, t-student = cauchy
  
  tau_att ~ dgamma(a_att, b_att) ## a_att e b_att vem nos dados
  tau_def ~ dgamma(a_def, b_def)
  
  sigma_att = 1/sqrt(tau_att)
  sigma_def = 1/sqrt(tau_def)
}
", file={model <- tempfile()})
```


```{r}
library(rjags)
# https://math.ntnu.edu.tw/~rtsai/104/bayes/jags/jags-OLR.pdf

load.module("bugs")
#load.module("mix")

G = 380
T = 20
sigma_sq_eff = 100

#
a_att <- 1
b_att <- 1

#
a_def <- 1
b_def <- 1

# 
sigma_sq_eff_size <- 2.5

## Dados
data <- read.csv("../../data/2014_partidas_tidy.csv", header = TRUE, encoding = 'UTF-8')

n_sim <- 5000
jags.m <- jags.model(model, quiet = TRUE,
                     data = list(
                       G = G,
                       a_att= a_att,
                       a_def = a_def,
                       b_att = b_att,
                       b_def = b_def,
                       sigma_sq_eff = sigma_sq_eff,
                       sigma_sq_eff_size = sigma_sq_eff_size,
                       T = T,
                       h  = data$home_team_id,
                       a  = data$away_team_id,
                       y1 = data$home_team_score,
                       y2 = data$away_team_score
                       
                     ), 
                    n.chains = 1, n.adapt = 1000)

model_cat_dp <- coda.samples(jags.m, 
                             c("y1_tilde", "y2_tilde"),
                             n.iter = n_sim, n.burnin = floor(n_sim/2), quiet = T)
```

```{r fig.height=10, fig.width=10}
summary(model_cat_dp)
plot(model_cat_dp)
```

```{r}
model_cat_parameters <- coda.samples(jags.m, 
                             c("home", "mu_att", "mu_def", "sigma_att", "sigma_def", "bn_size"),
                             n.iter = n_sim, n.burnin = floor(n_sim/2), quiet = T)
```

```{r}
plot(model_cat_parameters)
summary(model_cat_parameters)
```

