---
title: "Modelo poisson misto zero inflado JAGs"
output: html_notebook
---
# Código do modelo no Jags

```{r echo=TRUE}
cat("
model
{   
C <- 10000

  for(g in 1:G) {  
    ## Criar vetor de zeros fora (passado como argumento)
    
    # Mandante
    ## zeros1[g] <- 0 
    zeros1[g] ~ dpois(fg1[g])
    fg1[g] <- -log(L1[g]) + C
    lambda1[g] = exp(home + att[h[g]] + def[a[g]]) # h e a são passados nos dados
    L1[g] <- p_home * equals(y1[g], 0) + (1 - p_home) * (exp(-lambda1[g]) * lambda1[g] ^ y1[g]) / y1_factorial[g]
    
    # Visitante
    ## zeros2[g] <- 0 
    zeros2[g] ~ dpois(fg2[g])
    fg2[g] <- -log(L2[g]) + C
    lambda2[g] = exp(att[a[g]] + def[h[g]])
    L2[g] <- p_away * equals(y2[g], 0) + (1 - p_away) * (exp(-lambda2[g]) * lambda2[g] ^ y2[g]) / y2_factorial[g]
    
    # Mandante predicao
    y1_indicator[g] ~ dbin(p_home, 1)
    y1_aux[g] ~ dpois(lambda1[g])
    y1_tilde[g] = y1_aux[g] * (1 - y1_indicator[g])

    # Visitante predicao
    y2_indicator[g] ~ dbin(p_away, 1)
    y2_aux[g] ~ dpois(lambda2[g])
    y2_tilde[g] = y2_aux[g] * (1 - y2_indicator[g])
  }
  
  for(t in 1:(T-1)) {
    att_raw[t] ~ dnorm(mu_att, tau_att)  ## tau = 1/sigma2
    def_raw[t] ~ dnorm(mu_def, tau_def)
    att[t] = att_raw[t]
    def[t] = def_raw[t]
  }
  
  att[T] = 0
  def[T] = 0
  
  tau_eff = 1/sigma_sq_eff ## sigma_sq_eff passado nos dados
  tau_size = 1/sigma_sq_eff_size ## sigma_sq_eff_size passado nos dados
   
  mu_att ~ dnorm(0, tau_eff)
  mu_def ~ dnorm(0, tau_eff)
  
  home ~ dnorm(0, tau_eff)
  
  tau_att ~ dgamma(a_att, b_att) ## a_att e b_att vem nos dados
  tau_def ~ dgamma(a_def, b_def)
  
  sigma_att = 1/sqrt(tau_att)
  sigma_def = 1/sqrt(tau_def)
  
  p_home ~ dbeta(alpha, beta) 
  p_away ~ dbeta(alpha, beta) 
}
", file={model <- tempfile()})
```


```{r}
library(rjags)
# https://math.ntnu.edu.tw/~rtsai/104/bayes/jags/jags-OLR.pdf

load.module("bugs")
#load.module("mix")

G = 380
T = 20
sigma_sq_eff = 100

#
a_att <- 1
b_att <- 1

#
a_def <- 1
b_def <- 1

#
alpha <- 2
beta <- 5
zeros <- rep(0, G)

# 
sigma_sq_eff_size <- 2.5

## Dados
data <- read.csv("../../data/2014_partidas_tidy.csv", header = TRUE, encoding = 'UTF-8')

n_sim <- 5000
jags.m <- jags.model(model, quiet = TRUE,
                     data = list(
                       G = G,
                       a_att= a_att,
                       a_def = a_def,
                       b_att = b_att,
                       b_def = b_def,
                       sigma_sq_eff = sigma_sq_eff,
                       sigma_sq_eff_size = sigma_sq_eff_size,
                       T = T,
                       h  = data$home_team_id,
                       a  = data$away_team_id,
                       y1 = data$home_team_score,
                       y2 = data$away_team_score,
                       alpha = alpha,
                       beta = beta,
                       y1_factorial = factorial(data$home_team_score),
                       y2_factorial = factorial(data$away_team_score),
                       zeros1 = zeros,
                       zeros2 = zeros
                     ), 
                    n.chains = 1, n.adapt = 1000)

model_cat_dp <- coda.samples(jags.m, 
                             c("y1_tilde", "y2_tilde"),
                             n.iter = n_sim, n.burnin = floor(n_sim/2), quiet = T)
```

```{r fig.height=10, fig.width=10}
summary(model_cat_dp)
plot(model_cat_dp)
```

```{r}
model_cat_parameters <- coda.samples(jags.m, 
                             c("home", "mu_att", "mu_def", "sigma_att", "sigma_def"),
                             n.iter = n_sim, n.burnin = floor(n_sim/2), quiet = T)
```

```{r}
plot(model_cat_parameters)
summary(model_cat_parameters)
acf(model_cat_parameters)
```

